name: testquick
description: Test for the company Quick, Chat.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Responsive
  flutter_screenutil: ^4.0.3+1
  # Get for state management
  get: ^3.25.4
  # Service locator
  get_it: ^6.0.0
  # Value equality
  equatable: ^1.2.6
  # Validate Forms
  formz: ^0.3.2
  # Functional programming thingies
  dartz: ^0.9.2
  # Remote API
  data_connection_checker: ^0.3.4
  # Firebase
  firebase_core: ^1.0.3
  firebase_analytics: ^7.1.1
  firebase_auth: ^1.0.3
  cloud_firestore: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.7+1
  flutter_launcher_icons: ^0.9.0

# Native Splash App
flutter_native_splash:
  color: "#5B61B9"
  image: assets/images/logo.png

# Launcher Icon App
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # Custom Assets
  assets:
    - assets/images/

  # Custom Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700